# **Lógica Proposicional**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
valor1 = np.array([True, True, False, False])
valor2 = np.array([True, False, True, False])

In [11]:
conjuncao = valor1 & valor2
disjuncao1 = valor1 | valor2
disjuncao2 = valor1 ^ valor2
condicao = ~valor1 | valor2
bicondicao = valor1 == valor2

### **Conjunção (E)**

In [ ]:
pd.DataFrame(
    {
        "Valor P": valor1,
        "Valor Q": valor2,
        "Conjunção (P ^ Q)": conjuncao,
    }
)

   Valor P  Valor Q  Conjunção (P ^ Q)
0     True     True               True
1     True    False              False
2    False     True              False
3    False    False              False

### **Disjunção (OU)**

In [ ]:
pd.DataFrame(
    {
        "Valor P": valor1,
        "Valor Q": valor2,
        "Disjunção (P v Q)": disjuncao1,
    }
)

   Valor P  Valor Q  Disjunção (P v Q)
0     True     True               True
1     True    False               True
2    False     True               True
3    False    False              False

### **Disjunção (OU... OU)**

In [ ]:
pd.DataFrame(
    {
        "Valor P": valor1,
        "Valor Q": valor2,
        "Disjunção (P ⊻ Q)": disjuncao2,
    }
)

   Valor P  Valor Q  Disjunção (P ⊻ Q)
0     True     True              False
1     True    False               True
2    False     True               True
3    False    False              False

### **Condicional (SE... ENTÃO)**

In [ ]:
pd.DataFrame(
    {
        "Valor P": valor1,
        "Valor Q": valor2,
        "Condição (P -> Q)": condicao,
    }
)

   Valor P  Valor Q  Condição (P -> Q)
0     True     True               True
1     True    False              False
2    False     True               True
3    False    False               True

### **Bicondicional (SE E SOMENTE SE)**

In [ ]:
pd.DataFrame(
    {
        "Valor P": valor1,
        "Valor Q": valor2,
        "Bicondição (P <-> Q)": bicondicao,
    }
)

   Valor P  Valor Q  Bicondição (P <-> Q)
0     True     True                  True
1     True    False                 False
2    False     True                 False
3    False    False                  True